server:
  port: 35000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/econexion
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # o validate / create-drop según lo que quieras
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

jwt:
  secret: unSuperSecretoDePrueba1234567890
  expiration-minutes: 120
